columns:
  Code:
    dtype: Int64
    rename: fao_area
  Name_En:
    dtype: string
    rename: fao_area_name
  Ocean_Group_En:
    dtype: string
    rename: ocean
  FARegion_Group_En:
    dtype: string
    rename: region
  sosi_grouping:
    dtype: string
    from:
      column: Code
      transformation: create_sosi_grouping
primary_key:
  - fao_area

