value_set_columns:
  - fao_area
  - asfis_code
  - location
columns:
  fao_area:
    dtype: string
    rename: fao_area_label
  isscaap_code:
    dtype: Int64
  isscaap_group:
    dtype: string
    transformation: "lambda col: col.str.strip('\"')"
  asfis_code:
    dtype: string
    restrictions: 
      - ['lambda col: col.str.split(";").explode().str.len().astype("Int64").eq(3)', 'filter']
  common_name:
    dtype: string
  species_name:
    dtype: string
  location:
    dtype: string
  status_year:
    dtype: Int64
  tier:
    dtype: Int64
  status:
    dtype: string
    restrictions: 
      - ["lambda col: col.isin(['U', 'M', 'O', 'X', pd.NA])", "filter"]
  uncertainty:
    dtype: string
    restrictions:
      - ["lambda col: (col.isin(['L', 'M', 'H', pd.NA]))", "filter"]
  grsf_stock_id:
    dtype: string
    restrictions:
      - ["lambda col: col.notna()", "filter"]
  fao_areas:
    dtype: object
    from:
      column: fao_area
      transformation: "lambda col: col.str.split(':').str[1:].str.join(', ')"
    transformation: "lambda col: col.str.split(', ').apply(lambda x: [int(i) for i in x])"
primary_key: grsf_stock_id

