"""remove taxonomic_codes from stock_reference

Revision ID: 5e8cd48d019e
Revises: 16d17166946c
Create Date: 2026-03-12 12:26:58.194312

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5e8cd48d019e'
down_revision = '16d17166946c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_reference', schema=None) as batch_op:
        batch_op.drop_column('taxonomic_codes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_reference', schema=None) as batch_op:
        batch_op.add_column(sa.Column('taxonomic_codes', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
