"""initial commit

Revision ID: 83879aa2f226
Revises: 
Create Date: 2026-03-12 12:04:49.179039

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '83879aa2f226'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asfis',
    sa.Column('asfis_code', sa.String(length=3), nullable=False),
    sa.Column('common_name', sa.String(), nullable=True),
    sa.Column('family', sa.String(), nullable=True),
    sa.Column('isscaap_code', sa.Integer(), nullable=True),
    sa.Column('order', sa.String(), nullable=True),
    sa.Column('species_name', sa.String(), nullable=False),
    sa.Column('taxonomic_code', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('asfis_code', name=op.f('pk_asfis'))
    )
    op.create_table('countries',
    sa.Column('country_un_code', sa.Integer(), nullable=False),
    sa.Column('iso3_code', sa.String(length=3), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('country_un_code', name=op.f('pk_countries'))
    )
    op.create_table('fao_areas',
    sa.Column('fao_area', sa.Integer(), nullable=False),
    sa.Column('fao_area_name', sa.String(), nullable=False),
    sa.Column('ocean', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('sosi_grouping', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('fao_area', name=op.f('pk_fao_areas')),
    sa.UniqueConstraint('fao_area_name', name=op.f('uq_fao_areas_fao_area_name'))
    )
    op.create_table('stock_reference',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('asfis_codes', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('fao_areas', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('species_names', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('common_name', sa.String(), nullable=False),
    sa.Column('taxonomic_codes', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('sosi_grouping', sa.String(), nullable=False),
    sa.Column('isscaap_code', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('status_year', sa.Integer(), nullable=True),
    sa.Column('tier', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('uncertainty', sa.String(), nullable=True),
    sa.Column('sosi_edition', sa.Integer(), nullable=False),
    sa.Column('sosi_record_type', sa.String(), nullable=False),
    sa.Column('ocean', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk_stock_reference'))
    )
    with op.batch_alter_table('stock_reference', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_reference_asfis_codes'), ['asfis_codes'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_reference_fao_areas'), ['fao_areas'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_reference_isscaap_code'), ['isscaap_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_reference_sosi_grouping'), ['sosi_grouping'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_reference_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_reference_tier'), ['tier'], unique=False)

    op.create_table('aquaculture',
    sa.Column('environment_code', sa.String(length=2), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('country_un_code', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(length=5), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('fao_area', sa.Integer(), nullable=False),
    sa.Column('asfis_code', sa.String(length=3), nullable=False),
    sa.Column('production', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['country_un_code'], ['countries.country_un_code'], name=op.f('fk_aquaculture_country_un_code_countries')),
    sa.ForeignKeyConstraint(['fao_area'], ['fao_areas.fao_area'], name=op.f('fk_aquaculture_fao_area_fao_areas')),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk_aquaculture'))
    )
    with op.batch_alter_table('aquaculture', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aquaculture_asfis_code'), ['asfis_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_aquaculture_country_un_code'), ['country_un_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_aquaculture_fao_area'), ['fao_area'], unique=False)
        batch_op.create_index(batch_op.f('ix_aquaculture_year'), ['year'], unique=False)

    op.create_table('capture',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('country_un_code', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(length=5), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('fao_area', sa.Integer(), nullable=False),
    sa.Column('asfis_code', sa.String(length=3), nullable=False),
    sa.Column('production', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['country_un_code'], ['countries.country_un_code'], name=op.f('fk_capture_country_un_code_countries')),
    sa.ForeignKeyConstraint(['fao_area'], ['fao_areas.fao_area'], name=op.f('fk_capture_fao_area_fao_areas')),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk_capture'))
    )
    with op.batch_alter_table('capture', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_capture_asfis_code'), ['asfis_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_capture_country_un_code'), ['country_un_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_capture_fao_area'), ['fao_area'], unique=False)
        batch_op.create_index(batch_op.f('ix_capture_year'), ['year'], unique=False)

    op.create_table('species_landings',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('asfis_code', sa.String(), nullable=False),
    sa.Column('fao_area', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('production', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['fao_area'], ['fao_areas.fao_area'], name=op.f('fk_species_landings_fao_area_fao_areas')),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk_species_landings'))
    )
    op.create_table('stock_landings',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('landings', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['uid'], ['stock_reference.uid'], name=op.f('fk_stock_landings_uid_stock_reference')),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk_stock_landings'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_landings')
    op.drop_table('species_landings')
    with op.batch_alter_table('capture', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_capture_year'))
        batch_op.drop_index(batch_op.f('ix_capture_fao_area'))
        batch_op.drop_index(batch_op.f('ix_capture_country_un_code'))
        batch_op.drop_index(batch_op.f('ix_capture_asfis_code'))

    op.drop_table('capture')
    with op.batch_alter_table('aquaculture', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aquaculture_year'))
        batch_op.drop_index(batch_op.f('ix_aquaculture_fao_area'))
        batch_op.drop_index(batch_op.f('ix_aquaculture_country_un_code'))
        batch_op.drop_index(batch_op.f('ix_aquaculture_asfis_code'))

    op.drop_table('aquaculture')
    with op.batch_alter_table('stock_reference', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_reference_tier'))
        batch_op.drop_index(batch_op.f('ix_stock_reference_status'))
        batch_op.drop_index(batch_op.f('ix_stock_reference_sosi_grouping'))
        batch_op.drop_index(batch_op.f('ix_stock_reference_isscaap_code'))
        batch_op.drop_index(batch_op.f('ix_stock_reference_fao_areas'))
        batch_op.drop_index(batch_op.f('ix_stock_reference_asfis_codes'))

    op.drop_table('stock_reference')
    op.drop_table('fao_areas')
    op.drop_table('countries')
    op.drop_table('asfis')
    # ### end Alembic commands ###
