"""add sg to production_mixin

Revision ID: edf247a9df71
Revises: 5e8cd48d019e
Create Date: 2026-03-19 15:43:03.615027

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "edf247a9df71"
down_revision = "5e8cd48d019e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("aquaculture", schema=None) as batch_op:
        batch_op.add_column(sa.Column("sosi_grouping", sa.String(), nullable=True))

    with op.batch_alter_table("capture", schema=None) as batch_op:
        batch_op.add_column(sa.Column("sosi_grouping", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("capture", schema=None) as batch_op:
        batch_op.drop_column("sosi_grouping")

    with op.batch_alter_table("aquaculture", schema=None) as batch_op:
        batch_op.drop_column("sosi_grouping")

    # ### end Alembic commands ###
