all_flag: ALL
extract:
  required: False
  abbreviation: e
  help: "Download files from source and update them in the cache"
  nargs: "*"
load:
  required: False
  abbreviation: l
  help: "Load files into drive"
  nargs: "*"
plot:
  required: False
  abbreviation: p
  help: "Plot figures produced"
  nargs: "*"
output:
  required: False
  abbreviation: o
  help: "Save the output files locally to a directory"
  nargs: "?"
  const: "./output"
verbosity:
  required: False
  abbreviation: v
  help: "Verbosity for logger"
  choices: ["DEBUG", "INFO", "ERROR", "WARN"]
  default: "INFO"
