name: SOSI 2026 Data Pipeline

on:
  workflow_dispatch:
    inputs:
      extract_tables:
        description: "Tables to extract from source (space-separated, or enter 'all' to extract all)"
        required: False
        default: ''
      load_files:
        description: "Figures and tables to load to drive (space-separated, or enter 'all' to load all)"
        required: False
        default: ''
      log_level:
        description: "Set log verbosity"
        type: choice
        options:
          - DEBUG
          - INFO
          - WARNING
          - ERROR
        default: 'INFO'

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14' 
          cache: 'pip'           

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Cache Processed Tables
        uses: actions/cache@v4
        with:
          path: .cache/  
          key: tables-${{ github.ref_name }}-${{ github.run_id }}
          restore-keys: |
            tables-${{ github.ref_name }}-

      - name: Decode and Create Google Credentials File
        run: |
          echo "${{ secrets.GSA_CREDENTIALS_BASE64 }}" | base64 --decode > gsa_credentials.json
          echo "${{ secrets.GOOGLE_OAUTH_CREDENTIALS_BASE64 }}" | base64 --decode > google_oauth_credentials.json

      - name: Run SOSI Pipeline
        env:
          GOOGLE_OAUTH_CREDENTIALS_PATH: ${{ github.workspace }}/google_oauth_credentials.json
          GOOGLE_SERVICE_ACCOUNT_CREDENTIALS_PATH: ${{ github.workspace }}/gsa_credentials.json
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          BRANCH: ${{ github.head_ref || github.ref_name }}
          LOG_LEVEL: ${{ inputs.log_level }}
          TABLES_TO_EXTRACT: ${{ inputs.extract_tables }}
          FILES_TO_LOAD: ${{ inputs.load_files }}
        run: |
          CMD="python -m src.main"
          TTE_LOWER=$(echo "$TABLES_TO_EXTRACT" | tr '[:upper:]' '[:lower:]')

          if [ -n "$TABLES_TO_EXTRACT" ]; then
            if [ "$TTE_LOWER" == 'all' ]; then
              CMD="$CMD -e"
            else
              CMD="$CMD -e $TABLES_TO_EXTRACT"
            fi
          fi

          if [ -n "$FILES_TO_LOAD" ]; then
            if [ "${FILES_TO_LOAD,,}" == 'all' ]; then
              CMD="$CMD -l"
            else
              CMD="$CMD -l $FILES_TO_LOAD"
            fi
          fi

          if [ -n "$LOG_LEVEL" ]; then
            CMD="$CMD -v $LOG_LEVEL"
          fi

          echo "Running command: $CMD"
          $CMD

      - name: Upload Logs as Artifacts
        if: always() 
        uses: actions/upload-artifact@v4
        with:
          name: execution-logs
          path: logs/*.log
          retention-days: 5 
